apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio-base.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "istio-base.name" . }}
    helm.sh/chart: {{ include "istio-base.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
  {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- $s := "selector:" }}
  {{- $s }}
    app.kubernetes.io/name: {{ include "istio-base.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
