{{- if .Values.clusterrolebinding.enabled -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "istio.fullname" . }}
  labels:
    app: {{ template "istio.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "istio.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "istio.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}