{{- if .Values.virtualservice.enabled -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "istio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "istio.name" . }}
    helm.sh/chart: {{ include "istio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "istio.fullname" . }}
  {{- with .Values.virtualservice.http }}
  http:
    {{- toYaml . | nindent 6 }}
  {{- end }}
{{- end -}}
