apiVersion: v1
kind: Service
metadata:
  name: {{ include "istio.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "istio.name" . }}
    helm.sh/chart: {{ include "istio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- with .Values.service }}
  {{- range .ports }}
  - {{ toYaml . }}
  {{- end }} 
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "istio.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
