# Default values for istio-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicaCount: 1
  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: HTTP
      name: http

ingress:
  enabled: false

gateway:
  selector:
    app: istio-ingressgateway     # DEFAULT
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - firstcontactcrypto.com
        - studio.firstcontactcrypto.com
      tls:
        httpsRedirect: true
    - port:
        name: https
        number: 443
        protocol: HTTPS
      hosts:
        - firstcontactcrypto.com
        - studio.firstcontactcrypto.com
      tls:
        mode: SIMPLE
        serverCertificate: /etc/certs/servicecert.pem
        privateKey: /etc/certs/privatekey.pem



