# Default values for istio-base.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

deployment:
  replicaCount: 1
  image:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: HTTP
      name: http

ingress:
  enabled: false

gateway:
  selector:
    app: istio-ingressgateway     # DEFAULT
  servers:
    - port:
        name: http
        number: 80
        protocol: HTTP
      hosts:
        - foo.com
        - bar.foo.com
      tls:
        httpsRedirect: true
    - port:
        name: https
        number: 443
        protocol: HTTPS
      hosts:
        - foo.com
        - bar.foo.com
      tls:
        mode: SIMPLE
        serverCertificate: /etc/certs/servicecert.pem
        privateKey: /etc/certs/privatekey.pem

virtualservice:
  hosts:
    - bar.foo.com
  gateways: []
  http:
    - match:
      - uri:
          prefix: "/wpcatalog"
      - uri:
          prefix: "/consumercatalog"
      rewrite:
        uri: "/newcatalog"
      route:
        - destination:
            host: reviews.prod.svc.cluster.local
            subset: v2
    - route:
      - destination:
          host: reviews.prod.svc.cluster.local
          subset: v1
  tls: []
  tcp: []


destinationrule:
  host: ratings.prod.svc.cluster.local
  trafficPolicy:
    portLevelSettings:
    - port:
        number: 80
      loadBalancer:
        simple: LEAST_CONN
    - port:
        number: 9080
      loadBalancer:
        simple: ROUND_ROBIN
  subsets: []